---
title: "Heteroskedasticity"
format: html
---

## C1 [SLEEP75]

> Consider the following model to explain sleeping behavior:
>
> $$sleep = \beta_0 + \beta_1 totwrk + \beta_2 educ + \beta_3 age + \beta_4 age^2 + \beta_5 yngkid + \beta_6 male + u.$$
>
> (i) Write down a model that allows the variance of $u$ to differ between men and women. The variance should not depend on other factors.
>
> (ii) Use the data in SLEEP75 to estimate the parameters of the model for heteroskedasticity. (You have to first estimate the `sleep` equation by OLS to obtain the OLS residuals.) Is the estimated variance of $u$ higher for men or for women?
>
> (iii) Is the variance of $u$ statistically different for men and for women?

## C2 [HPRICE1]

> (i) Use the data in HPRICE1 to obtain the heteroskedasticity-robust standard errors for equation (8.17). Discuss any important differences with the usual standard errors.
> (ii) Repeat part (i) for equation (8.18).
> (iii) What does this example suggest about heteroskedasticity and the transformation used for the dependent variable?

## C3

> Apply the full White test for heteroskedasticity [see equation (8.19)] to equation (8.18). Using the chi-square form of the statistic, obtain the $p$-value. What do you conclude?

## C4 [VOTE1]

> Use VOTE1 for this exercise.
> (i) Estimate a model with `voteA` as the dependent variable and `prtystrA`, `democA`, $\log(expendA)$, and $\log(expendB)$ as independent variables. Obtain the OLS residuals, $\hat{u}_i$, and regress these on all of the independent variables. Explain why you obtain $R^2 = 0$.
> (ii) Now, compute the Breusch-Pagan test for heteroskedasticity. Use the $F$ statistic version and report the $p$-value.
> (iii) Compute the special case of the White test for heteroskedasticity, again using the $F$ statistic form. How strong is the evidence for heteroskedasticity now?

## C5 [PNTSPRD]

> Use the data in PNTSPRD for this exercise.
> (i) The variable `sprdcvr` is a binary variable equal to one if the Las Vegas point spread for a college basketball game was covered. The expected value of `sprdcvr`, say $\mu$, is the probability that the spread is covered in a randomly selected game. Test $H_0: \mu = 0.5$ against $H_1: \mu \neq 0.5$ at the 10% significance level and discuss your findings. (*Hint*: This is easily done using a $t$ test by regressing `sprdcvr` on an intercept only.)
> (ii) How many games in the sample of 553 were played on a neutral court?
> (iii) Estimate the linear probability model
> 
> $$sprdcvr = \beta_0 + \beta_1 favhome + \beta_2 neutral + \beta_3 fav25 + \beta_4 und25 + u$$
> 
> and report the results in the usual form. (Report the usual OLS standard errors and the heteroskedasticity-robust standard errors.) Which variable is most significant, both practically and statistically?
> (iv) Explain why, under the null hypothesis $H_0: \beta_1 = \beta_2 = \beta_3 = \beta_4 = 0$, there is no heteroskedasticity in the model.
> (v) Use the usual $F$ statistic to test the hypothesis in part (iv). What do you conclude?
> (vi) Given the previous analysis, would you say that it is possible to systematically predict whether the Las Vegas spread will be covered using information available prior to the game?

## C6

> In Example 7.12, we estimated a linear probability model for whether a young man was arrested during 1986:
> 
> $$arr86 = \beta_0 + \beta_1 pcnv + \beta_2 avgsen + \beta_3 tottime + \beta_4 ptime86 + \beta_5 qemp86 + u.$$
> 
> (i) Using the data in CRIME1, estimate this model by OLS and verify that all fitted values are strictly between zero and one. What are the smallest and largest fitted values?
> (ii) Estimate the equation by weighted least squares, as discussed in Section 8-5.
> (iii) Use the WLS estimates to determine whether `avgsen` and `tottime` are jointly significant at the 5% level.

## C7 [LOANAPP]

> Use the data in LOANAPP for this exercise.
> (i) Estimate the equation in part (iii) of Computer Exercise C8 in Chapter 7, computing the heteroskedasticity-robust standard errors. Compare the 95% confidence interval on $\beta_{white}$ with the nonrobust confidence interval.
> (ii) Obtain the fitted values from the regression in part (i). Are any of them less than zero? Are any of them greater than one? What does this mean about applying weighted least squares?

## C8 [GPA1]

> Use the data set GPA1 for this exercise.
> (i) Use OLS to estimate a model relating `colGPA` to `hsGPA`, `ACT`, `skipped`, and `PC`. Obtain the OLS residuals.
> (ii) Compute the special case of the White test for heteroskedasticity. In the regression of $\hat{u}_i^2$ on $\hat{colGPA}_i, \hat{colGPA}_i^2$, obtain the fitted values, say $\hat{h}_i$.
> (iii) Verify that the fitted values from part (ii) are all strictly positive. Then, obtain the weighted least squares estimates using weights $1/\hat{h}_i$. Compare the weighted least squares estimates for the effect of skipping lectures and the effect of PC ownership with the corresponding OLS estimates. What about their statistical significance?
> (iv) In the WLS estimation from part (iii), obtain heteroskedasticity-robust standard errors. In other words, allow for the fact that the variance function estimated in part (ii) might be misspecified. Do the standard errors change much from part (iii)?

## C9

> In Example 8.7, we computed the OLS and a set of WLS estimates in a cigarette demand equation.
> (i) Obtain the OLS estimates in equation (8.35).
> (ii) Obtain the $\hat{h}_i$ used in the WLS estimation of equation (8.36) and reproduce equation (8.36). From this equation, obtain the *unweighted* residuals and fitted values; call these $\hat{u}_i$ and $\hat{y}_i$, respectively. (For example, in Stata®, the unweighted residuals and fitted values are given by default.)
> (iii) Let $\tilde{u}_i = \hat{u}_i / \sqrt{\hat{h}_i}$ and $\tilde{y}_i = \hat{y}_i / \sqrt{\hat{h}_i}$ be the weighted quantities. Carry out the special case of the White test for heteroskedasticity by regressing $\tilde{u}_i^2$ on $\tilde{y}_i, \tilde{y}_i^2$, being sure to include an intercept, as always. Do you find heteroskedasticity in the weighted residuals?
> (iv) What does the finding from part (iii) imply about the proposed form of heteroskedasticity used in obtaining (8.36)?
> (v) Obtain valid standard errors for the WLS estimates that allow the variance function to be misspecified.

## C10 [401KSUBS]

> Use the data set 401KSUBS for this exercise.
> (i) Using OLS, estimate a linear probability model for `e401k`, using as explanatory variables `inc`, $inc^2$, `age`, $age^2$, and `male`. Obtain both the usual OLS standard errors and the heteroskedasticity-robust versions. Are there any important differences?
> (ii) In the special case of the White test for heteroskedasticity, where we regress the squared OLS residuals on a quadratic in the OLS fitted values, $\hat{u}_i^2$ on $\hat{y}_i, \hat{y}_i^2, i = 1, \dots, n$, argue that the probability limit of the coefficient on $\hat{y}_i$ should be one, the probability limit of the coefficient on $\hat{y}_i^2$ should be $-1$, and the probability limit of the intercept should be zero. {*Hint*: Remember that $\text{Var}(y|x_1, \dots, x_k) = p(\mathbf{x})[1 - p(\mathbf{x})]$, where $p(\mathbf{x}) = \beta_0 + \beta_1 x_1 + \dots + \beta_k x_k$.}
> (iii) For the model estimated in part (i), obtain the White test and see if the coefficient estimates roughly correspond to the theoretical values described in part (ii).
> (iv) After verifying that the fitted values from part (i) are all between zero and one, obtain the weighted least squares estimates of the linear probability model. Do they differ in important ways from the OLS estimates?

## C11 [401KSUBS]

> Use the data in 401KSUBS for this question, restricting the sample to $fsize = 1$.
> (i) To the model estimated in Table 8.1, add the interaction term, $e401k \cdot inc$. Estimate the equation by OLS and obtain the usual and robust standard errors. What do you conclude about the statistical significance of the interaction term?
> (ii) Now estimate the more general model by WLS using the same weights, $1/inc_i$, as in Table 8.1. Compute the usual and robust standard error for the WLS estimator. Is the interaction term statistically significant using the robust standard error?
> (iii) Discuss the WLS coefficient on `e401k` in the more general model. Is it of much interest by itself? Explain.
> (iv) Reestimate the model by WLS but use the interaction term $e401k \cdot (inc - 30)$; the average income in the sample is about 29.44. Now interpret the coefficient on `e401k`.

## C12 [MEAP00]

> Use the data in MEAP00 to answer this question.
> (i) Estimate the model
> 
> $$math4 = \beta_0 + \beta_1 lunch + \beta_2 \log(enroll) + \beta_3 \log(exppp) + u$$
> 
> by OLS and obtain the usual standard errors and the fully robust standard errors. How do they generally compare?
> (ii) Apply the special case of the White test for heteroskedasticity. What is the value of the $F$ test? What do you conclude?
> (iii) Obtain $\hat{g}_i$ as the fitted values from the regression $\log(\hat{u}_i^2)$ on $\hat{math4}_i, \hat{math4}_i^2$, where $\hat{math4}_i$ are the OLS fitted values and the $\hat{u}_i$ are the OLS residuals. Let $\hat{h}_i = \exp(\hat{g}_i)$. Use the $\hat{h}_i$ to obtain WLS estimates. Are there big differences with the OLS coefficients?
> (iv) Obtain the standard errors for WLS that allow misspecification of the variance function. Do these differ much from the usual WLS standard errors?
> (v) For estimating the effect of spending on `math4`, does OLS or WLS appear to be more precise?

## C13 [FERTIL2]

> Use the data in FERTIL2 to answer this question.
> (i) Estimate the model
> 
> $$children = \beta_0 + \beta_1 age + \beta_2 age^2 + \beta_3 educ + \beta_4 electric + \beta_5 urban + u$$
> 
> and report the usual and heteroskedasticity-robust standard errors. Are the robust standard errors always bigger than the nonrobust ones?
> (ii) Add the three religious dummy variables and test whether they are jointly significant. What are the $p$-values for the nonrobust and robust tests?
> (iii) From the regression in part (ii), obtain the fitted values $\hat{y}$ and the residuals, $\hat{u}$. Regress $\hat{u}^2$ on $\hat{y}, \hat{y}^2$ and test the joint significance of the two regressors. Conclude that heteroskedasticity is present in the equation for `children`.
> (iv) Would you say the heteroskedasticity you found in part (iii) is practically important?

## C14 [BEAUTY]

> Use the data in BEAUTY for this question.
> (i) Using the data pooled for men and women, estimate the equation
> 
> $$lwage = \beta_0 + \beta_1 belavg + \beta_2 abvavg + \beta_3 female + \beta_4 educ + \beta_5 exper + \beta_6 exper^2 + u,$$
> 
> and report the results using heteroskedasticity-robust standard errors below coefficients. Are any of the coefficients surprising in either their signs or magnitudes? Is the coefficient on `female` practically large and statistically significant?
> (ii) Add interactions of `female` with all other explanatory variables in the equation from part (i) (five interactions in all). Compute the usual $F$ test of joint significance of the five interactions and a heteroskedasticity-robust version. Does using the heteroskedasticity-robust version change the outcome in any important way?
> (iii) In the full model with interactions, determine whether those involving the looks variables—$female \cdot belavg$ and $female \cdot abvavg$—are jointly significant. Are their coefficients practically small?