---
title: "Simultaneous Equations Models"
format: html
---

## C1 \[SMOKE\]

> Use SMOKE for this exercise. (i) A model to estimate the effects of smoking on annual income (perhaps through lost work days due to illness, or productivity effects) is $$\log(income) = \beta_0 + \beta_1 cigs + \beta_2 educ + \beta_3 age + \beta_4 age^2 + u_1,$$ where `cigs` is number of cigarettes smoked per day, on average. How do you interpret $\beta_1$? (ii) To reflect the fact that cigarette consumption might be jointly determined with income, a demand for cigarettes equation is $$cigs = \gamma_0 + \gamma_1 \log(income) + \gamma_2 educ + \gamma_3 age + \gamma_4 age^2 + \gamma_5 \log(cigpric) + \gamma_6 restaurn + u_2,$$ where `cigpric` is the price of a pack of cigarettes (in cents) and `restaurn` is a binary variable equal to unity if the person lives in a state with restaurant smoking restrictions. Assuming these are exogenous to the individual, what signs would you expect for $\gamma_5$ and $\gamma_6$?

> (iii) Under what assumption is the income equation from part (i) identified?
> (iv) Estimate the income equation by OLS and discuss the estimate of $\beta_1$.
> (v) Estimate the reduced form for `cigs`. (Recall that this entails regressing `cigs` on all exogenous variables.) Are $\log(cigpric)$ and `restaurn` significant in the reduced form?
> (vi) Now, estimate the income equation by 2SLS. Discuss how the estimate of $\beta_1$ compares with the OLS estimate.
> (vii) Do you think that cigarette prices and restaurant smoking restrictions are exogenous in the income equation?

## C2 \[MROZ\]

> Use MROZ for this exercise. (i) Reestimate the labor supply function in Example 16.5, using $\log(hours)$ as the dependent variable. Compare the estimated elasticity (which is now constant) to the estimate obtained from equation (16.24) at the average hours worked. (ii) In the labor supply equation from part (i), allow `educ` to be endogenous because of omitted ability. Use `motheduc` and `fatheduc` as IVs for `educ`. Remember, you now have two endogenous variables in the equation. (iii) Test the overidentifying restrictions in the 2SLS estimation from part (ii). Do the IVs pass the test?

## C3 \[OPENNESS\]

> Use the data in OPENNESS for this exercise. (i) Because $\log(pcinc)$ is insignificant in both (16.22) and the reduced form for `open`, drop it from the analysis. Estimate (16.22) by OLS and IV without $\log(pcinc)$. Do any important conclusions change? (ii) Still leaving $\log(pcinc)$ out of the analysis, is `land` or $\log(land)$ a better instrument for `open`? (*Hint*: Regress `open` on each of these separately and jointly.) (iii) Now, return to (16.22). Add the dummy variable `oil` to the equation and treat it as exogenous. Estimate the equation by IV. Does being an oil producer have a ceteris paribus effect on inflation?

## C4 \[CONSUMP\]

> Use the data in CONSUMP for this exercise. (i) In Example 16.7, use the method from Section 15-5 to test the single overidentifying restriction in estimating (16.35). What do you conclude? (ii) Campbell and Mankiw (1990) use *second* lags of all variables as IVs because of potential data measurement problems and informational lags. Reestimate (16.35), using only $gc_{t-2}$, $gy_{t-2}$, and $r3_{t-2}$ as IVs. How do the estimates compare with those in (16.36)? (iii) Regress $gy_t$ on the IVs from part (ii) and test whether $gy_t$ is sufficiently correlated with them. Why is this important?

## C5

> Use the *Economic Report of the President* (2005 or later) to update the data in CONSUMP, at least through 2003. Reestimate equation (16.35). Do any important conclusions change?

## C6 \[CEMENT\]

> Use the data in CEMENT for this exercise. (i) A static (inverse) supply function for the monthly growth in cement price ($gprc$) as a function of growth in quantity ($gcem$) is $$gprc_t = \alpha_1 gcem_t + \beta_0 + \beta_1 gprcpet + \beta_2 feb_t + \dots + \beta_{12} dec_t + u_t^s,$$ where $gprcpet$ (growth in the price of petroleum) is assumed to be exogenous and $feb, \dots, dec$ are monthly dummy variables. What signs do you expect for $\alpha_1$ and $\beta_1$? Estimate the equation by OLS. Does the supply function slope upward? (ii) The variable $gdefs$ is the monthly growth in real defense spending in the United States. What do you need to assume about $gdefs$ for it to be a good IV for $gcem$? Test whether $gcem$ is partially correlated with $gdefs$. (Do not worry about possible serial correlation in the reduced form.) Can you use $gdefs$ as an IV in estimating the supply function?

> (iii) Shea (1993) argues that the growth in output of residential (`gres`) and nonresidential (`gnon`) construction are valid instruments for `gcem`. The idea is that these are demand shifters that should be roughly uncorrelated with the supply error $u_t^s$. Test whether `gcem` is partially correlated with `gres` and `gnon`; again, do not worry about serial correlation in the reduced form.
> (iv) Estimate the supply function, using `gres` and `gnon` as IVs for `gcem`. What do you conclude about the static supply function for cement? \[The dynamic supply function is, apparently, upward sloping; see Shea (1993).\]

## C7 \[CRIME4\]

> Refer to Example 13.9 and the data in CRIME4. (i) Suppose that, after differencing to remove the unobserved effect, you think $\Delta\log(polpc)$ is simultaneously determined with $\Delta\log(crmrte)$; in particular, increases in crime are associated with increases in police officers. How does this help to explain the positive coefficient on $\Delta\log(polpc)$ in equation (13.33)? (ii) The variable `taxpc` is the taxes collected per person in the county. Does it seem reasonable to exclude this from the crime equation? (iii) Estimate the reduced form for $\Delta\log(polpc)$ using pooled OLS, including the potential IV, $\Delta\log(taxpc)$. Does it look like $\Delta\log(taxpc)$ is a good IV candidate? Explain. (iv) Suppose that, in several of the years, the state of North Carolina awarded grants to some counties to increase the size of their county police force. How could you use this information to estimate the effect of additional police officers on the crime rate?

## C8 \[FISH\]

> Use the data set in FISH, which comes from Graddy (1995), to do this exercise. The data set is also used in Computer Exercise C9 in Chapter 12. Now, we will use it to estimate a demand function for fish. (i) Assume that the demand equation can be written, in equilibrium for each time period, as $$\log(totqty_t) = \alpha_1 \log(avgprc_t) + \beta_{t0} + \beta_{t1} mon_t + \beta_{t2} tues_t + \beta_{t3} wed_t + \beta_{t4} thurs_t + u_{t1},$$ so that demand is allowed to differ across days of the week. Treating the price variable as endogenous, what additional information do we need to estimate the demand-equation parameters consistently? (ii) The variables `wave2` and `wave3` are measures of ocean wave heights over the past several days. What two assumptions do we need to make in order to use `wave2` and `wave3` as IVs for $\log(avgprc_t)$ in estimating the demand equation? (iii) Regress $\log(avgprc_t)$ on the day-of-the-week dummies and the two wave measures. Are `wave2` and `wave3` jointly significant? What is the $p$-value of the test? (iv) Now, estimate the demand equation by 2SLS. What is the 95% confidence interval for the price elasticity of demand? Is the estimated elasticity reasonable? (v) Obtain the 2SLS residuals, $\hat{u}_{t1}$. Add a single lag, $\hat{u}_{t-1,1}$ in estimating the demand equation by 2SLS. Remember, use $\hat{u}_{t-1,1}$ as its own instrument. Is there evidence of AR(1) serial correlation in the demand equation errors? (vi) Given that the supply equation evidently depends on the wave variables, what two assumptions would we need to make in order to estimate the price elasticity of supply? (vii) In the reduced form equation for $\log(avgprc_t)$, are the day-of-the-week dummies jointly significant? What do you conclude about being able to estimate the supply elasticity?

## C9 \[AIRFARE\]

> For this exercise, use the data in AIRFARE, but only for the year 1997. (i) A simple demand function for airline seats on routes in the United States is $$\log(passen) = \beta_{10} + \alpha_1 \log(fare) + \beta_{11} \log(dist) + \beta_{12} [\log(dist)]^2 + u_1,$$

> where \* `passen` = average passengers per day, \* `fare` = average airfare, and \* `dist` = the route distance (in miles).
>
> If this is truly a demand function, what should be the sign of $\alpha_1$? (ii) Estimate the equation from part (i) by OLS. What is the estimated price elasticity? (iii) Consider the variable `concen`, which is a measure of market concentration. (Specifically, it is the share of business accounted for by the largest carrier.) Explain in words what we must assume to treat `concen` as exogenous in the demand equation. (iv) Now assume `concen` is exogenous to the demand equation. Estimate the reduced form for $\log(fare)$ and confirm that `concen` has a positive (partial) effect on $\log(fare)$. (v) Estimate the demand function using IV. Now what is the estimated price elasticity of demand? How does it compare with the OLS estimate? (vi) Using the IV estimates, describe how demand for seats depends on route distance.

## C10 \[AIRFARE\]

> Use the entire panel data set in AIRFARE for this exercise. The demand equation in a simultaneous equations unobserved effects model is $$\log(passen_{it}) = \theta_{t1} + \alpha_1 \log(fare_{it}) + a_{i1} + u_{it1},$$ where we absorb the distance variables into $a_{i1}$. (i) Estimate the demand function using fixed effects, being sure to include year dummies to account for the different intercepts. What is the estimated elasticity? (ii) Use fixed effects to estimate the reduced form $$\log(fare_{it}) = \theta_{t2} + \pi_{21} concen_{it} + a_{i2} + v_{it2}.$$ Perform the appropriate test to ensure that $concen_{it}$ can be used as an IV for $\log(fare_{it})$. (iii) Now estimate the demand function using the fixed effects transformation along with IV, as in equation (16.42). What is the estimated elasticity? Is it statistically significant?

## C11 \[EXPENDSHARES\]

> A common method for estimating *Engel curves* is to model expenditure shares as a function of total expenditure, and possibly demographic variables. A common specification has the form $$sgood = \beta_0 + \beta_1 ltotexpend + demographics + u,$$ where `sgood` is the fraction of spending on a particular good out of total expenditure and `ltotexpend` is the log of total expenditure. The sign and magnitude of $\beta_1$ are of interest across various expenditure categories. To account for the potential endogeneity of `ltotexpend`—which can be viewed as an omitted variables or simultaneous equations problem, or both—the log of family income is often used as an instrumental variable. Let `lincome` denote the log of family income. For the remainder of this question, use the data in EXPENDSHARES, which comes from Blundell, Duncan, and Pendakur (1998). (i) Use `sfood`, the share of spending on food, as the dependent variable. What is the range of values of `sfood`? Are you surprised there are no zeros? (ii) Estimate the equation $$sfood = \beta_0 + \beta_1 ltotexpend + \beta_2 age + \beta_3 kids + u \qquad [16.43]$$ by OLS and report the coefficient on `ltotexpend`, $\hat{\beta}_{OLS,1}$, along with its heteroskedasticity-robust standard error. Interpret the result.

> (iii) Using `lincome` as an IV for `ltotexpend`, estimate the reduced form equation for `ltotexpend`; be sure to include `age` and `kids`. Assuming `lincome` is exogenous in (16.43), is `lincome` a valid IV for `ltotexpend`?
> (iv) Now estimate (16.43) by instrumental variables. How does $\hat{\beta}_{IV,1}$ compare with $\hat{\beta}_{OLS,1}$? What about the robust 95% confidence intervals?
> (v) Use the test in Section 15-5 to test the null hypothesis that `ltotexpend` is exogenous in (16.43). Be sure to report and interpret the $p$-value. Are there any overidentifying restrictions to test?
> (vi) Substitute `salcohol` for `sfood` in (16.43) and estimate the equation by OLS and 2SLS. Now what do you find for the coefficients on `ltotexpend`?

## C12 \[PRISON.DTA\]

> Use the data in PRISON.DTA to answer the following questions. Refer to Example 16.8. In the data set, variables beginning with “g” are growth rates from one year to the next, obtained as the changes in the natural log. For example, $gcriv_{it} = \log(criv_{it}) - \log(criv_{i,t-1})$. Variables beginning with “c” are changes in levels from one year to the next, for example, $cunem_{it} = unem_{it} - unem_{i,t-1}$. (i) Estimate the equation $$gcriv_{it} = \xi_t + \alpha_1 gpris_{it} + \beta_1 gincpc_{it} + \beta_2 gpolc_{it} + \beta_3 cag0\_14_{it} + \beta_4 cag15\_17_{it} + \beta_5 cag18\_24_{it} + \beta_6 cag25\_34_{it} + \beta_7 cunem_{it} + \beta_8 cblack_{it} + \beta_9 cmetro_{it} + \Delta u_{it}$$ by OLS and verify that you obtain $\hat{\alpha}_1 = -0.181 (\text{se} = 0.048)$. The parameters $\xi_t$ are to remind you to include year dummies for 1981 through 1993. (ii) Estimate the reduced form equation for $gpris_{it}$, where $final1_{it}$ and $final2_{it}$ are the instruments: $$gpris_{it} = \eta_t + \gamma_1 final1_{it} + \gamma_2 final2_{it} + \pi_1 gincpc_{it} + \pi_2 gpolpc_{it} + \pi_3 cag0\_14_{it} + \pi_4 cag15\_17_{it} + \pi_5 cag18\_24_{it} + \pi_6 cag25\_34_{it} + \pi_7 cunem_{it} + \pi_8 cblack_{it} + \pi_9 cmetro_{it} + \Delta u_{it}$$ Verify that $\gamma_1$ and $\gamma_2$ are both negative. Are they each statistically significant? What is the $F$ statistic for $H_0: \gamma_1 = \gamma_2 = 0$? (Remember again to put in a full set of year dummies.) (iii) Obtain the 2SLS estimates of the equation in part (i), using $final1_{it}$ and $final2_{it}$ as instruments for $gpris_{it}$. Verify that you obtain $\hat{\alpha}_1 = -1.032 (\text{se} = 0.370)$. (iv) If you have access to econometrics software that computes standard errors robust to heteroskedasticity and serial correlation, obtain them for the 2SLS estimate in part (iii). What happens to the standard error of $\hat{\alpha}_1$? (v) Reestimate the reduced form in part (ii) using the differences, $\Delta final1_{it}$ and $\Delta final2_{it}$, as the instruments. (You will lose 1980 in differencing the instruments.) Do $\Delta final1_{it}$ and $\Delta final2_{it}$ seem like sufficiently strong instruments for $gpris_{it}$? In particular, do you prefer using the differences or levels as the IVs? Estimate the reduced form in part (ii) dropping 1980 to be sure that you reach your conclusion on instrument strength using the same set of data.
