---
title: "Advanced Panel Data Methods"
format: html
---

## C1 [RENTAL]

> Use the data in RENTAL for this exercise. The data on rental prices and other variables for college towns are for the years 1980 and 1990. The idea is to see whether a stronger presence of students affects rental rates. The unobserved effects model is
>
> $$\log(rent_{it}) = \beta_0 + \delta_0 y90_t + \beta_1 \log(pop_{it}) + \beta_2 \log(avginc_{it}) + \beta_3 pctstu_{it} + a_i + u_{it},$$
>
> where `pop` is city population, `avginc` is average income, and `pctstu` is student population as a percentage of city population (during the school year).
>
> (i) Estimate the equation by pooled OLS and report the results in standard form. What do you make of the estimate on the 1990 dummy variable? What do you get for $\hat{\beta}_{pctstu}$?
>
> (ii) Are the standard errors you report in part (i) valid? Explain.
>
> (iii) Now, difference the equation and estimate by OLS. Compare your estimate of $\beta_{pctstu}$ with that from part (i). Does the relative size of the student population appear to affect rental prices?
>
> (iv) Estimate the model by fixed effects to verify that you get identical estimates and standard errors to those in part (iii).

## C2 [CRIME4]

> Use CRIME4 for this exercise.
>
> (i) Reestimate the unobserved effects model for crime in Example 13.9 but use fixed effects rather than differencing. Are there any notable sign or magnitude changes in the coefficients? What about statistical significance?
>
> (ii) Add the logs of each wage variable in the data set and estimate the model by fixed effects. How does including these variables affect the coefficients on the criminal justice variables in part (i)?
>
> (iii) Do the wage variables in part (ii) all have the expected sign? Explain. Are they jointly significant?

## C3 [JTRAIN]

> For this exercise, we use JTRAIN to determine the effect of the job training grant on hours of job training per employee. The basic model for the three years is
>
> $$hrsemp_{it} = \beta_0 + \delta_1 d88_t + \delta_2 d89_t + \beta_1 grant_{it} + \beta_2 grant_{i,t-1} + \beta_3 \log(employ_{it}) + a_i + u_{it}.$$
>
> (i) Estimate the equation using fixed effects. How many firms are used in the FE estimation? How many total observations would be used if each firm had data on all variables (in particular, `hrsemp`) for all three years?
>
> (ii) Interpret the coefficient on `grant` and comment on its significance.

> (iii) Is it surprising that $grant_{-1}$ is insignificant? Explain.
> (iv) Do larger firms provide their employees with more or less training, on average? How big are the differences? (For example, if a firm has 10% more employees, what is the change in average hours of training?)

## C4

> In Example 13.8, we used the unemployment claims data from Papke (1994) to estimate the effect of enterprise zones on unemployment claims. Papke also uses a model that allows each city to have its own time trend:
>
> $$\log(uclms_{it}) = a_i + c_i t + \beta_1 ez_{it} + u_{it},$$
>
> where $a_i$ and $c_i$ are both unobserved effects. This allows for more heterogeneity across cities.
> (i) Show that, when the previous equation is first differenced, we obtain
>
> $$\Delta \log(uclms_{it}) = c_i + \beta_1 \Delta ez_{it} + \Delta u_{it}, \quad t = 2, \dots, T.$$
>
> Notice that the differenced equation contains a fixed effect, $c_i$.
> (ii) Estimate the differenced equation by fixed effects. What is the estimate of $\beta_1$? Is it very different from the estimate obtained in Example 13.8? Is the effect of enterprise zones still statistically significant?
> (iii) Add a full set of year dummies to the estimation in part (ii). What happens to the estimate of $\beta_1$?

## C5 

> (i) In the wage equation in Example 14.4, explain why dummy variables for occupation might be important omitted variables for estimating the union wage premium.
> (ii) If every man in the sample stayed in the same occupation from 1981 through 1987, would you need to include the occupation dummies in a fixed effects estimation? Explain.
> (iii) Using the data in WAGEPAN include eight of the occupation dummy variables in the equation and estimate the equation using fixed effects. Does the coefficient on `union` change by much? What about its statistical significance?

## C6

> Add the interaction term $union_{it} \cdot t$ to the equation estimated in Table 14.2 to see if wage *growth* depends on union status. Estimate the equation by random and fixed effects and compare the results.

## C7 [MURDER]

> Use the state-level data on murder rates and executions in MURDER for the following exercise.
> (i) Consider the unobserved effects model
>
> $$mrdrte_{it} = \eta_t + \beta_1 exec_{it} + \beta_2 unem_{it} + a_i + u_{it},$$
>
> where $\eta_t$ simply denotes different year intercepts and $a_i$ is the unobserved state effect. If past executions of convicted murderers have a deterrent effect, what should be the sign of $\beta_1$? What sign do you think $\beta_2$ should have? Explain.
> (ii) Using just the years 1990 and 1993, estimate the equation from part (i) by pooled OLS. Ignore the serial correlation problem in the composite errors. Do you find any evidence for a deterrent effect?
> (iii) Now, using 1990 and 1993, estimate the equation by fixed effects. You may use first differencing because you are only using two years of data. Is there evidence of a deterrent effect? How strong?
> (iv) Compute the heteroskedasticity-robust standard error for the estimation in part (ii).
> (v) Find the state that has the largest number for the execution variable in 1993. (The variable `exec` is total executions in 1991, 1992, and 1993.) How much bigger is this value than the next highest value?
> (vi) Estimate the equation using first differencing, dropping Texas from the analysis. Compute the usual and heteroskedasticity-robust standard errors. Now, what do you find? What is going on?
> (vii) Use all three years of data and estimate the model by fixed effects. Include Texas in the analysis. Discuss the size and statistical significance of the deterrent effect compared with only using 1990 and 1993.

## C8 [MATHPNL]

> Use the data in MATHPNL for this exercise. You will do a fixed effects version of the first differencing done in Computer Exercise 11 in Chapter 13. The model of interest is
>
> $$math4_{it} = \delta_1 y94_t + \dots + \delta_5 y98_t + \gamma_1 \log(rexpp_{it}) + \gamma_2 \log(rexpp_{i,t-1}) + \psi_1 \log(enrol_{it}) + \psi_2 lunch_{it} + a_i + u_{it},$$
>
> where the first available year (the base year) is 1993 because of the lagged spending variable.
>
> (i) Estimate the model by pooled OLS and report the usual standard errors. You should include an intercept along with the year dummies to allow $a_i$ to have a nonzero expected value. What are the estimated effects of the spending variables? Obtain the OLS residuals, $\hat{v}_{it}$.
>
> (ii) Is the sign of the $lunch_{it}$ coefficient what you expected? Interpret the magnitude of the coefficient. Would you say that the district poverty rate has a big effect on test pass rates?
>
> (iii) Compute a test for AR(1) serial correlation using the regression $\hat{v}_{it}$ on $\hat{v}_{i,t-1}$. You should use the years 1994 through 1998 in the regression. Verify that there is strong positive serial correlation and discuss why.
>
> (iv) Now, estimate the equation by fixed effects. Is the lagged spending variable still significant?
>
> (v) Why do you think, in the fixed effects estimation, the enrollment and lunch program variables are jointly insignificant?
>
> (vi) Define the total, or long-run, effect of spending as $\theta_1 = \gamma_1 + \gamma_2$. Use the substitution $\gamma_1 = \theta_1 - \gamma_2$ to obtain a standard error for $\hat{\theta}_1$. [*Hint*: Standard fixed effects estimation using $\log(rexpp_{it})$ and $z_{it} = \log(rexpp_{i,t-1}) - \log(rexpp_{it})$ as explanatory variables should do it.]

## C9 [PENSION]

> The file PENSION contains information on participant-directed pension plans for U.S. workers. Some of the observations are for couples within the same family, so this data set constitutes a small cluster sample (with cluster sizes of two).
>
> (i) Ignoring the clustering by family, use OLS to estimate the model
>
> $$pctstck = \beta_0 + \beta_1 choice + \beta_2 prftshr + \beta_3 female + \beta_4 age + \beta_5 educ + \beta_6 finc25 + \beta_7 finc35 + \beta_8 finc50 + \beta_9 finc75 + \beta_{10} finc100 + \beta_{11} finc101 + \beta_{12} wealth89 + \beta_{13} stckin89 + \beta_{14} irain89 + u,$$
>
> where the variables are defined in the data set. The variable of most interest is `choice`, which is a dummy variable equal to one if the worker has a choice in how to allocate pension funds among different investments. What is the estimated effect of `choice`? Is it statistically significant?
>
> (ii) Are the income, wealth, stock holding, and IRA holding control variables important? Explain.
>
> (iii) Determine how many different families there are in the data set.
>
> (iv) Now, obtain the standard errors for OLS that are robust to cluster correlation within a family. Do they differ much from the usual OLS standard errors? Are you surprised?
>
> (v) Estimate the equation by differencing across only the spouses within a family. Why do the explanatory variables asked about in part (ii) drop out in the first-differenced estimation?
>
> (vi) Are any of the remaining explanatory variables in part (v) significant? Are you surprised?

## C10 [AIRFARE]

> Use the data in AIRFARE for this exercise. We are interested in estimating the model
>
> $$\log(fare_{it}) = \eta_t + \beta_1 concen_{it} + \beta_2 \log(dist_i) + \beta_3 [\log(dist_i)]^2 + a_i + u_{it}, \quad t = 1, \dots, 4,$$
>
> where $\eta_t$ means that we allow for different year intercepts.
>
> (i) Estimate the above equation by pooled OLS, being sure to include year dummies. If $\Delta concen = 0.10$, what is the estimated percentage increase in `fare`?
>
> (ii) What is the usual OLS 95% confidence interval for $\beta_1$? Why is it probably not reliable? If you have access to a statistical package that computes fully robust standard errors, find the fully robust 95% CI for $\beta_1$. Compare it to the usual CI and comment.

> (iii) Describe what is happening with the quadratic in $\log(dist)$. In particular, for what value of $dist$ does the relationship between $\log(fare)$ and $dist$ become positive? [*Hint*: First figure out the turning point value for $\log(dist)$, and then exponentiate.] Is the turning point outside the range of the data?
> (iv) Now estimate the equation using random effects. How does the estimate of $\beta_1$ change?
> (v) Now estimate the equation using fixed effects. What is the FE estimate of $\beta_1$? Why is it fairly similar to the RE estimate? (*Hint*: What is $\hat{\theta}$ for RE estimation?)
> (vi) Name two characteristics of a route (other than distance between stops) that are captured by $a_i$. Might these be correlated with $concen_{it}$?
> (vii) Are you convinced that higher concentration on a route increases airfares? What is your best estimate?

## C11

> This question assumes that you have access to a statistical package that computes standard errors robust to arbitrary serial correlation and heteroskedasticity for panel data methods.
> (i) For the pooled OLS estimates in Table 14.1, obtain the standard errors that allow for arbitrary serial correlation (in the composite errors, $v_{it} = a_i + u_{it}$) and heteroskedasticity. How do the robust standard errors for `educ`, `married`, and `union` compare with the nonrobust ones?
> (ii) Now obtain the robust standard errors for the fixed effects estimates that allow arbitrary serial correlation and heteroskedasticity in the idiosyncratic errors, $u_{it}$. How do these compare with the nonrobust FE standard errors?
> (iii) For which method, pooled OLS or FE, is adjusting the standard errors for serial correlation more important? Why?

## C12 [ELEM94_95]

> Use the data in ELEM94_95 to answer this question. The data are on elementary schools in Michigan. In this exercise, we view the data as a cluster sample, where each school is part of a district cluster.
> (i) What are the smallest and largest number of schools in a district? What is the average number of schools per district?
> (ii) Using pooled OLS (that is, pooling across all 1,848 schools), estimate a model relating `lavgsal` to `bs`, `lenrol`, `lstaff`, and `lunch`; see Computer Exercise 11 from Chapter 9. What are the coefficient and standard error on `bs`?
> (iii) Obtain the standard errors that are robust to cluster correlation within district (and also heteroskedasticity). What happens to the $t$ statistic for `bs`?
> (iv) Still using pooled OLS, drop the four observations with $bs > 0.5$ and obtain $\hat{\beta}_{bs}$ and its cluster-robust standard error. Now is there much evidence for a salary-benefits tradeoff?
> (v) Estimate the equation by fixed effects, allowing for a common district effect for schools within a district. Again drop the observations with $bs > 0.5$. Now what do you conclude about the salary-benefits tradeoff?
> (vi) In light of your estimates from parts (iv) and (v), discuss the importance of allowing teacher compensation to vary systematically across districts via a district fixed effect.

## C13 [DRIVING]

> The data set DRIVING includes state-level panel data (for the 48 continental U.S. states) from 1980 through 2004, for a total of 25 years. Various driving laws are indicated in the data set, including the alcohol level at which drivers are considered legally intoxicated. There are also indicators for “per se” laws—where licenses can be revoked without a trial—and seat belt laws. Some economic and demographic variables are also included.
> (i) How is the variable `totfatrte` defined? What is the average of this variable in the years 1980, 1992, and 2004? Run a regression of `totfatrte` on dummy variables for the years 1981 through 2004, and describe what you find. Did driving become safer over this period? Explain.
> (ii) Add the variables `bac08`, `bac10`, `perse`, `sbprim`, `sbsecon`, `sl70plus`, `gdl`, `perc14_24`, `unem`, and `vehicmilespc` to the regression from part (i). Interpret the coefficients on `bac8` and `bac10`. Do per se laws have a negative effect on the fatality rate? What about having a primary seat belt law? (Note that if a law was enacted sometime within a year the fraction of the year is recorded in place of the zero-one indicator.)

> (iii) Reestimate the model from part (ii) using fixed effects (at the state level). How do the coefficients on $bac08$, $bac10$, $perse$, and $sbprim$ compare with the pooled OLS estimates? Which set of estimates do you think is more reliable?
> (iv) Suppose that $vehicmilespc$, the number of miles driven per capita, increases by 1,000. Using the FE estimates, what is the estimated effect on $totfatrte$? Be sure to interpret the estimate as if explaining to a layperson.
> (v) If there is serial correlation or heteroskedasticity in the idiosyncratic errors of the model then the standard errors in part (iii) are invalid. If possible, use “cluster” robust standard errors for the fixed effects estimates. What happens to the statistical significance of the policy variables in part (iii)?

## C14 [AIRFARE]

> Use the data set in AIRFARE to answer this question. The estimates can be compared with those in Computer Exercise 10, in this chapter.
> (i) Compute the time averages of the variable $concen$; call these $concenbar$. How many different time averages can there be? Report the smallest and the largest.
> (ii) Estimate the equation
> 
> $$lfare_{it} = \beta_0 + \delta_1 y98_t + \delta_2 y99_t + \delta_3 y00_t + \beta_1 concen_{it} + \beta_2 ldist_i + \beta_3 ldistsq_i + \gamma_1 concenbar_i + a_i + u_{it}$$
> 
> by random effects. Verify that $\hat{\beta}_1$ is identical to the FE estimate computed in C10.
> (iii) If you drop $ldist$ and $ldistsq$ from the estimation in part (i) but still include $concenbar_i$, what happens to the estimate of $\beta_1$? What happens to the estimate of $\gamma_1$?
> (iv) Using the equation in part (ii) and the usual RE standard error, test $H_0: \gamma_1 = 0$ against the two-sided alternative. Report the $p$-value. What do you conclude about RE versus FE for estimating $\beta_1$ in this application?
> (v) If possible, for the test in part (iv) obtain a $t$-statistic (and, therefore, $p$-value) that is robust to arbitrary serial correlation and heteroskedasticity. Does this change the conclusion reached in part (iv)?

## C15 [COUNTYMURDERS]

> Use the data in COUNTYMURDERS to answer this question. The data set covers murders and executions (capital punishment) for 2,197 counties in the United States. See also Computer Exercise C16 in Chapter 13.
> (i) Consider the model
> 
> $$murdrate_{it} = \theta_t + \delta_0 execs_{it} + \delta_1 execs_{i,t-1} + \delta_2 execs_{i,t-2} + \delta_3 execs_{i,t-3} + \beta_5 percblack_{it} + \beta_6 percmale_{it} + \beta_7 perc1019_{it} + \beta_8 perc2029_{it} + a_i + u_{it},$$
> 
> where $\theta_t$ represents a different intercept for each time period, $a_i$ is the county fixed effect, and $u_{it}$ is the idiosyncratic error. Why does it make sense to include lags of the key variable, $execs$, in the equation?
> (ii) Apply OLS to the equation from part (i) and report the estimates of $\delta_0, \delta_1, \delta_2,$ and $\delta_3$, along with the usual pooled OLS standard errors. Do you estimate that executions have a deterrent effect on murders? Provide an explanation that involves $a_i$.
> (iii) Now estimate the equation in part (i) using fixed effects to remove $a_i$. What are the new estimates of the $\delta_j$? Are they very different from the estimates from part (ii)?
> (iv) Obtain the long-run propensity from estimates in part (iii). Using the usual FE standard errors, is the LRP statistically different from zero?
> (v) If possible, obtain the standard errors for the FE estimates that are robust to arbitrary heteroskedasticity and serial correlation in the $\{u_{it}\}$. What happens to the statistical significance of the $\delta_j$? What about the estimated LRP?

## C16 [WAGEPAN]

> Use the data in WAGEPAN.DTA to answer the following questions.
> (i) Using $lwage$ as the dependent variable, estimate a model that only contains an intercept and the year dummies $d81$ through $d87$. Use pooled OLS, RE, FE, and FD (where in the latter...

...case you difference the year dummies, along with $lwage$, and omit an overall constant in the FD regression). What do you conclude about the coefficients on the year dummies?
> (ii) Add the time-constant variables $educ$, $black$, and $hisp$ to the model, and estimate it by OLS and RE. How do the coefficients compare? What happens if you estimate the equation by FE?
> (iii) What do you conclude about the four estimation methods when the model includes only variables that change just across $t$ or just across $i$?
> (iv) Now estimate the equation
>
> $$lwage_{it} = \alpha_1 + \beta_1 union_{it} + \beta_2 married_{it} + \beta_3 educ_i + \beta_4 black_i + \beta_5 hisp_i + c_i + u_{it}$$
>
> by random effects. Do the coefficients seem reasonable? How do the nonrobust and cluster-robust standard errors compare?
> (v) Now estimate the equation
>
> $$lwage_{it} = \alpha_1 + \beta_1 union_{it} + \beta_2 married_{it} + c_i + u_{it}$$
>
> by fixed effects, being sure to include the full set of time dummies to reflect the different intercepts. How do the estimates of $\beta_1$ and $\beta_2$ compare with those in part (iv)? Compute the usual FE standard errors and the cluster-robust standard errors. How do they compare?
> (vi) Obtain the time averages $\overline{union}_i$ and $\overline{married}_i$. Along with $educ$, $black$, and $hisp$, add these to the equation from part (iv). Verify that the CRE estimates of $\beta_1$ and $\beta_2$ are identical to the FE estimates.
> (vii) Obtain the robust, variable addition Hausman test. What do you conclude about RE versus FE?
> (viii) Let $educ$ have an interactive effect with both $union$ and $married$ and estimate the model by fixed effects. Are the interactions individually or jointly significant? Why are the coefficients on $union$ and $married$ now imprecisely estimated?
> (ix) Estimate the average partial effects of $union$ and $married$ for the model estimated in part (viii). How do these compare with the FE estimates from part (v)?
> (x) Verify that for the model in part (viii) the CRE estimates are the same as the FE estimates when they should be. (Hint: You need to include $\overline{union}_i$, $\overline{married}_i$, $educ_i \cdot \overline{union}_i$, and $educ_i \cdot \overline{married}_i$ in the CRE estimation.)

## C17 [SCHOOL93_98]

> Use the data in SCHOOL93_98 to answer the following questions. You should declare that the data set is a panel data set with `schid` as the cross-sectional identifier and `year` as the time identifier.
> (i) How many schools are there? Does each school have a record for each of the six years? Verify that `lavgrexpp` is missing for all schools in 1993.
> (ii) Create a selection indicator, $s$, that is equal to one if and only if you have nonmissing data on `math4`, `lavgrexpp`, `lunch`, and `lenrol`. Next, define a variable `tobs` to be the number of complete time periods per school. How many schools have all given years of available data (noting that 1993 is not available for any school when we use `lavgrexpp`)? Drop all schools with $tobs = 0$.
> (iii) Use random effects to estimate a model relating `math4` to `lavgrexpp`, `lunch`, and `lenrol`. Be sure to include a full set of year dummies. What is the estimated effect of school spending on `math4`? What is its cluster-robust $t$ statistic?
> (iv) Now estimate the model from part (iii) by fixed effects. What is the estimated spending effect and its robust confidence interval? How does it compare to the RE estimate from part (iii)?
> (v) Create the time averages of all of the explanatory variables in the RE/FE estimation, including the time dummies. You need to use the selection indicator constructed in part (ii). Verify that when you add these and estimate the equation by RE you obtain the FE estimates on the time-varying explanatory variables. What happens if you drop the time averages for $y95$, $y96$, $y97$, and $y98$?
> (vi) Is the random effects estimator rejected in favor of fixed effects? Explain.

## C18 [CARDKRUEGER]

> Use the data in CARDKRUEGER for this exercise. The data set comes from the well-known study by Card and Krueger (1994) concerning the effect of an increase in New Jersey's minimum wage on employment at fast food restaurants. On April 1, 1992, New Jersey increased its minimum wage from $4.25 to $5.05. The data set is a two-period panel data set with the same set of restaurants in Pennsylvania (PA, serving as the control) and New Jersey (NJ) in both periods. The before period is February 1992 and the after period is November 1992.
>
> (i) How many different restaurants are in the data set? How many of them are located in New Jersey?
>
> (ii) What is the range of values taken on by the variable `fte` (full-time equivalent employees)? What is the average value of `fte` across the entire sample? In February, what is the difference in average `fte` between PA and NJ?
>
> (iii) If you use November data to estimate the difference in mean `fte` between NJ and PA, what do you find? Is the difference statistically significant?
>
> (iv) Now obtain the difference-in-difference estimate of the effect of the minimum wage increase. Do this by regressing $\Delta fte$ on a constant and `nj`. Is the sign of the estimate what you expected? Is the estimate statistically different from zero?
>
> (v) In part (iv), add interactions between `nj` and each of `kfc`, `roys`, and `wendys`. Does it appear the effect of the minimum wage increase varies across type of restaurant?

## C19 [OPPZONE]

> Use the data in OPPZONE to answer the following questions. These data are at the census tract level for the state of Michigan. The years 2012 and 2015 act as control periods, prior to the passage of the Tax Cuts and Jobs Act, signed into law in December 2017. Many of the census tracts were designated to have an opportunity zone (OZ) prior to 2020. The idea is to use data from 2012, 2015, and 2020 to measure the effect of OZ designation on poverty rates measured at the census tract level. The binary variable `oppzone` does not change over time; it indicates if the tract is eventually designated an OZ in 2020. The variable `treat` is zero in all three years for a control tract. For a treated tract, it is zero in the first two years and equals one in 2020.
>
> (i) How many total census tracts are in the data set? How many include an OZ in 2020?
>
> (ii) Use just the year 2012 and run a regression with `poverty` as the dependent variable and `oppzone` as the only explanatory variable. What do you make of the positive coefficient on `oppzone`? Is its magnitude practical large? Is it statistically significant?
>
> (iii) What does part (ii) tell you about how OZs were designated? In particular, were OZs randomly assigned to census tracts?
>
> (iv) Use all three years to estimate an equation for `poverty` by fixed effects. You should include the year dummies `f2015` and `f2020` along with the variable `treat`. What is the estimated treatment effect? Is it practically large? Statistically significant? You should obtain standard errors that are robust to heteroskedasticity and any serial correlation.
>
> (v) Rather than use TWFE, use pooled OLS and include `oppzone`. Verify that the treatment effect is identical to that in part (iv). What does the large, positive coefficient on `oppzone` tell you? What do you make of the coefficient on `f2020`?
>
> (vi) Add $oppzone \cdot f2012$ to the regression in part (v) [or, equivalently, part (iv)]. This is an event-study regression. Is there evidence of pre-trends? What is the estimated treatment effect, and how does it compare with part (v)?
>
> (vii) To the analysis in part (v), add the interaction $oppzone \cdot (year - 2012)$, where the centering of `year` about 2012 is not needed but makes it easier to interpret the coefficient on `oppzone`. Now what is the estimated treatment effect? Is it smaller or larger in magnitude than in part (v)?
>
> (viii) What does the sign of the coefficient on $oppzone \cdot (year - 2012)$ indicate? Is this variable statistically significant at the 15% level? (You should use a cluster-robust standard error.)

## C20 [THEFTS.DTA]

> Use the data in THEFTS.DTA to answer the following questions. These data come from Di Tella and Schargrodsky (2004). Drop the data for $month = 7$ because the theft data are only for part of the month. This way, the pre-intervention period is $month \le 6$ and the post-intervention period is $month \ge 8$. The treatment in this case is whether a block includes a Jewish institution building because...

...extra police were assigned to such blocks after a terrorist attack on a main Jewish center in Buenos Aires in July 1994.

> (i) With the month of July dropped, how many months are there prior to the intervention? How many months post intervention? How many blocks are there in total? How many treated blocks, as indicated by the variable `sameblock`?
>
> (ii) Across all blocks and months, what is the most likely outcome of the variable `thefts`? What is the largest outcome? The average? Is it obvious that a linear model for `thefts` will be the most natural?
>
> (iii) Define the variable $treat_{it} = sameblock_i \cdot post_t$, where $post_t$ indicates being a post-intervention month. Run a pooled OLS regression of $thefts_{it}$ on 1, $sameblock_i$, $post_t$, $treat_{it}$ and report the estimated effect on monthly thefts on having more police assigned to a block. How large is the effect from a practical perspective? Report the usual OLS standard error and one that is robust to serial correlation and heteroskedasticity. Report a valid 95% confidence interval and discuss the statistical significance of the estimate.
>
> (iv) Verify that the two-way fixed effects estimate on $treat_{it}$ is the same as the POLS estimate.
>
> (v) Now allow the treatment effect to change in each of the post-treatment periods. You should estimate five different effects. Use the two-way fixed effects estimator in obtaining the five estimates. Do the estimates appear to vary a lot? Are they statistically different from one another? How does the average of the five effects compare with the single estimate in part (ii)?
>
> (vi) Without any controls, and using $month = 6$ as the control period, estimate the two pre-treatment effects along with the five treatment effects. Do you see evidence of pre-trends? How do the estimated effects and precisions compare with those in part (v)? (Hint: This can be done with a single regression by interacting `sameblock` with a suitable set of monthly indicators.)